name: Mirror Docker Hub to GHCR with Versioning

on:
  workflow_dispatch:       # 手动触发
    inputs:
      source_image:
        description: '源 Docker Hub 镜像名 (含 tag)'
        required: true
        default: 'uncleluo/mous:latest'
      target_image:
        description: '目标 GHCR 镜像名 (不含 ghcr.io/用户名)'
        required: true
        default: 'onesap'

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      # 1️⃣ 拉取仓库（必要时可以用 repo 文件）
      - name: Checkout repo
        uses: actions/checkout@v3

      # 2️⃣ 拉取 Docker Hub 镜像
      - name: Pull Docker Hub image
        run: |
          SOURCE=${{ github.event.inputs.source_image }}
          echo "Pulling Docker Hub image: $SOURCE ..."
          docker pull $SOURCE

      # 3️⃣ 登录 GHCR
      - name: Login to GHCR
        env:
          GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}  # 通过环境变量传递 token 更安全
        run: |
          echo "$GHCR_TOKEN" | docker login ghcr.io -u chiyuelao --password-stdin

      # 4️⃣ 检测是否有新版本
      - name: Detect new version
        run: |
          SOURCE=${{ github.event.inputs.source_image }}
          TARGET_NAME=${{ github.event.inputs.target_image }}
          DATE_TAG=$(date +%Y%m%d%H%M)  # 日期时间戳
          HIST_TARGET=ghcr.io/chiyuelao/$TARGET_NAME:$DATE_TAG
          LATEST_TARGET=ghcr.io/chiyuelao/$TARGET_NAME:latest

          # 尝试拉取 GHCR latest 镜像，如果失败就认为是新镜像
          if docker pull $LATEST_TARGET 2>/dev/null; then
            LATEST_DIGEST=$(docker inspect --format='{{index .RepoDigests 0}}' $LATEST_TARGET | cut -d'@' -f2)
            SOURCE_DIGEST=$(docker inspect --format='{{index .RepoDigests 0}}' $SOURCE 2>/dev/null || echo "")
            if [ "$LATEST_DIGEST" == "$SOURCE_DIGEST" ]; then
              echo "No new version detected. Skipping push."
              exit 0
            fi
          fi
          echo "New version detected. Will push to GHCR."
          echo "HIST_TARGET=$HIST_TARGET" >> $GITHUB_ENV
          echo "LATEST_TARGET=$LATEST_TARGET" >> $GITHUB_ENV

      # 5️⃣ 打标签并推送
      - name: Tag and push image
        run: |
          docker tag ${{ github.event.inputs.source_image }} $HIST_TARGET
          docker tag ${{ github.event.inputs.source_image }} $LATEST_TARGET
          echo "Pushing historical tag: $HIST_TARGET ..."
          docker push $HIST_TARGET
          echo "Pushing latest tag: $LATEST_TARGET ..."
          docker push $LATEST_TARGET
